Advanced: From chapter 10 to 11
Vretamoza/ElixirPath pull request #11
Opened 2022-03-02 03:26 UTC by Vretamoza

2022-03-02 14:01 UTC, juanhurtado10 requested changes

2022-03-02 14:01 UTC, juanhurtado10 commented on kv_umbrella/apps/kv/lib/kv/router.ex
> +@doc """
@Vretamoza please fix the doc's indentation

2022-03-02 19:26 UTC, Vretamoza commented on kv_umbrella/apps/kv/lib/kv/router.ex
> +      |> Task.await()
We use Task.await() to receive the message sent by the task created with async, because async tasks always send a response back.

2022-03-02 20:35 UTC, juanhurtado10 requested changes

2022-03-02 20:35 UTC, juanhurtado10 commented on kv_umbrella/apps/kv/lib/kv/registry.ex
> +      {:ok, pid} -> {:reply, pid, {names, refs}}
@Vretamoza this code fragment needs to be formatted. you can run `mix format` to do so

2022-03-03 11:19 UTC, Vretamoza commented on kv_umbrella/apps/kv/lib/kv/registry.ex
> +      {:ok, pid} -> {:reply, pid, {names, refs}}
I already did, but I uploaded the change in the next pull request.

2022-03-03 16:49 UTC, merged