Feature4 5
Vretamoza/ElixirPath pull request #13
Opened 2022-03-03 13:48 UTC by Vretamoza

2022-03-03 19:23 UTC, juanhurtado10 commented
@Vretamoza A rebase is required here :)

2022-03-03 19:25 UTC, juanhurtado10 requested changes

2022-03-03 19:25 UTC, juanhurtado10 commented on friends/lib/friends/person.ex
> +    |> cast(params, [:name, :age])
@Vretamoza what does `cast/3` do?

2022-03-03 19:25 UTC, juanhurtado10 commented on friends/lib/friends/person.ex
> +  def changeset(struct, params) do
@Vretamoza what is a changeset?

2022-03-04 13:29 UTC, Vretamoza commented on friends/lib/friends/person.ex
> +    |> cast(params, [:name, :age])
The cast function creates a changeset. Unlike the function change, it accepts three parameters, where the first one is the original data, the second is the changes we want to make, and the third is a list of fields that we allow to be changed.

2022-03-04 13:37 UTC, Vretamoza commented on friends/lib/friends/person.ex
> +  def changeset(struct, params) do
A changeset is a struct that saves some changes and some validation rules that allows us to save data in the database just if it is valid.

2022-03-04 13:54 UTC, merged