Metaprogramming
Vretamoza/ElixirPath pull request #14
Opened 2022-03-03 18:48 UTC by Vretamoza

2022-03-03 19:27 UTC, juanhurtado10 requested changes

2022-03-03 19:27 UTC, juanhurtado10 commented on metaprogramming/quote_unquote.exs
> +IO.inspect(quote do: sum(1, 2, 3))
@Vretamoza how do the quote and unquote works?

2022-03-03 19:27 UTC, juanhurtado10 commented on metaprogramming/domain_specific_languages.exs
> +          apply(__MODULE__, name, [])
@Vretamoza what does this line of code do?

2022-03-04 13:54 UTC, juanhurtado10 commented
@Vretamoza a rebase is required! Thanks

2022-03-04 14:19 UTC, Vretamoza commented on metaprogramming/quote_unquote.exs
> +IO.inspect(quote do: sum(1, 2, 3))
quotes returns the data structure representation of a function. With unquote we can inject code inside our quoted expressions.

2022-03-04 14:27 UTC, Vretamoza commented on metaprogramming/domain_specific_languages.exs
> +          apply(__MODULE__, name, [])
It is a function that allows us to run all the defined tests.

2022-03-04 15:38 UTC, juanhurtado10 commented on metaprogramming/domain_specific_languages.exs
> +          apply(__MODULE__, name, [])
tests? are you sure?

2022-03-04 15:39 UTC, juanhurtado10 approved these changes

2022-03-04 16:01 UTC, Vretamoza commented on metaprogramming/domain_specific_languages.exs
> +          apply(__MODULE__, name, [])
It saves the name of all defined tests in a module attribute so they can be executed by the run function. That's what I understood.

2022-03-04 20:18 UTC, juanhurtado10 commented on metaprogramming/domain_specific_languages.exs
> +          apply(__MODULE__, name, [])
@Vretamoza I was expecting an answer about the `apply/3` function which dynamically executes functions for the given module, but it is OK :)

2022-03-04 20:18 UTC, merged